[package]
name = "yes/voxl"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
camerashaker = "brittonfischer/camerashaker@0.1.0"
zoneplus = "mattschrubb/zoneplus@3.2.0"
simplepath = "jessekroeske/simplepath@2.2.2"
bytenet = "ffrostflame/bytenet@0.4.6"
rodux = "jessekroeske/rodux@3.0.0"
signal = "sleitnick/signal@2.0.3"
topbarplus = "1foreverhd/topbarplus@3.4.0"
cmdr = "evaera/cmdr@1.12.0"
jecs = "ukendio/jecs@0.9.0"
expressive-prompts = "miagobble/expressive-prompts@1.1.4"

[dev-dependencies]
profilestore = "sekuriyo-lotus/profilestore@1.0.4"